version: "3.7"
services:
  api_service:
    build: .
    networks:
      - backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - nelf_mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://nelf_mysql:3306/telegram_bot
    command: sh -c './wait-for nelf_mysql:3306 -- npm start'
  nelf_mysql:
    image: mysql
    networks:
      - backend
    restart: always
    ports:
      - "777:3306"
#    expose:
#      - 7777
    environment:
      MYSQL_DATABASE: telegram_bot
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
      MYSQL_ROOT_PASSWORD: bestuser
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
networks:
  backend:
    name: nelf-network
